version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo installing dependencies...
      - rm -rf dist
      - mkdir dist
      - cp src/expense-manager/* dist/
      - cd dist/
      - npm install --production
  build:
    commands:
      - echo attempting to zip
      - zip -r expense-manager-lambdas.zip . 
  post_build:
    commands:
      - find . -type f ! -name '*.zip' -delete
      - mkdir expense-manager
      - mv expense-manager-lambdas.zip expense-manager/
      - cd ..
artifacts:
  files:
    - "**/*"
  base-directory: 'dist/expense-manager'
  discard-paths: yes