version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo installing dependencies
      - rm -rf dist
      - mkdir dist
      - cd backend && npm install
      - cd app && npm install
      - cd ../..
  build:
    commands:
      - echo attempting to zip
      - cd backend && zip -r dependency_layer.zip *
      - cd app/srv && zip -r expense-manager-lambdas.zip *
      - cd ../../..
  post_build:
    commands:
      - mkdir dist/expense-manager
      - mv backend/dependency_layer.zip dist/expense-manager/
      - mv backend/app/srv/expense-manager-lambdas.zip dist/expense-manager/
      - aws s3 cp dist/expense-manager/expense-manager-lambdas.zip  s3://expense-manager-management --region eu-west-1
      - aws s3 cp dist/expense-manager/dependency_layer.zip  s3://expense-manager-management --region eu-west-1
      - aws lambda publish-layer-version --region eu-west-1 --layer-name expense-manager-dependencies-layer --s3-bucket expense-manager-management --s3-key dependency_layer.zip 
    	- aws lambda update-function-code --region eu-west-1 --s3-bucket expense-manager-management --s3-key expense-manager-lambdas.zip --function-name get-expense-categories 
	
artifacts:
  files:
    - "**/*"
  base-directory: 'dist/expense-manager'
  discard-paths: yes